name: vamboai
description: "VamboAI is a comprehensive Dart package designed to provide seamless integration with the Vambo AI API. It allows developers to leverage powerful language identification and translation capabilities in their applications. This package supports a wide range of languages, making it an essential tool for applications targeting diverse linguistic audiences, particularly those focusing on African languages."
version: 1.0.1
homepage: https://github.com/iamngoni/vamboai
repository: https://github.com/iamngoni/vamboai

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  meta: ^1.15.0

dev_dependencies:
  mockito: ^5.4.4
  test: 1.25.7
  very_good_analysis: ^5.0.1